spring:
  application:
    name: souplesse-pilates
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/souplesse_pilates}
    username: ${SPRING_DATASOURCE_USERNAME:pilates_user}
    password: ${SPRING_DATASOURCE_PASSWORD:pilates_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: imene7905@gmail.com
    password: gxstwinuubgmxhsb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  web:
    resources:
      static-locations: classpath:/static/

server:
  port: ${SERVER_PORT:8080}

app:
  mail:
    from: imene7905@gmail.com          
    studio-name: "Souplesse Pilates Studio"