spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/souplesse_pilates
    username: pilates_user
    password: pilates_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
